name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install dependencies for mock-server
        working-directory: ./mock-server
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create remote folder if not exists
        run: ssh -o StrictHostKeyChecking=no root@89.111.171.148 "mkdir -p /var/www/fo"

      - name: Upload build to server
        run: rsync -avz --delete ./dist/ root@89.111.171.148:/var/www/fo/

