name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install dependencies for mock-server
        working-directory: ./mock-server
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create remote folders if not exist
        run: |
          ssh -o StrictHostKeyChecking=no root@89.111.171.148 << 'ENDSSH'
            mkdir -p /var/www/fo
            mkdir -p /var/www/mock-server
          ENDSSH

      - name: Upload build to server
        run: rsync -avz --delete ./dist/ root@89.111.171.148:/var/www/fo/

      - name: Upload mock-server to server
        run: rsync -avz ./mock-server/ root@89.111.171.148:/var/www/mock-server/

      - name: Install and start mock-server on server
        run: |
          ssh -o StrictHostKeyChecking=no root@89.111.171.148 << 'ENDSSH'
            cd /var/www/mock-server
            yarn install --frozen-lockfile
            yarn build
            npm install -g pm2
            pm2 delete mock-server || true
            pm2 start yarn --name mock-server -- start
            pm2 save
          ENDSSH